/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistem.CRUD;
import static sistem.CRUD.listarUsuarios;
import sistem.Usuarios;

/**
 *
 * @author Pedro
 */
public class Telaadm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Telaadm.class.getName());

    /**
     * Creates new form Telaadm
     */
    
    private void limparCampos() {
    Campo_nome.setText("");
    Campo_email.setText("");
    Campo_senha.setText("");
    checkAdm.setSelected(false);
}

    
    private void atualizarTabela() {

    try {

        List<Usuarios> lista = CRUD.listarUsuarios();

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nome");
        modelo.addColumn("Email");
        modelo.addColumn("Senha");
        modelo.addColumn("Admin");

        for (Usuarios u : lista) {
            modelo.addRow(new Object[]{
                u.getId(),
                u.getNome(),
                u.getEmail(),
                u.getSenha(),
                u.isAdm()
            });
        }

        tabelaUsuarios.setModel(modelo);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
                "Erro ao atualizar tabela!");
    }
}

    
    public Telaadm(Usuarios usuario) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        btn_atualizar = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_adicionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Campo_nome = new javax.swing.JTextField();
        Campo_email = new javax.swing.JTextField();
        Campo_senha = new javax.swing.JPasswordField();
        checkAdm = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BEM VINDO ADMINISTRADOR");

        tabelaUsuarios.setBackground(new java.awt.Color(255, 102, 0));
        tabelaUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabelaUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaUsuarios);
        if (tabelaUsuarios.getColumnModel().getColumnCount() > 0) {
            tabelaUsuarios.getColumnModel().getColumn(0).setResizable(false);
            tabelaUsuarios.getColumnModel().getColumn(1).setResizable(false);
            tabelaUsuarios.getColumnModel().getColumn(2).setResizable(false);
        }

        btn_atualizar.setText("Atualizar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        btn_delete.setText("Apagar");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_adicionar.setText("Adicionar");
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NOME  :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("EMAIL  :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("SENHA :");

        Campo_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_emailActionPerformed(evt);
            }
        });

        Campo_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_senhaActionPerformed(evt);
            }
        });

        checkAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAdmActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ADMINISTRADOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btn_atualizar)
                        .addGap(33, 33, 33)
                        .addComponent(btn_adicionar)
                        .addGap(47, 47, 47)
                        .addComponent(btn_delete)
                        .addGap(51, 51, 51)
                        .addComponent(btn_editar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Campo_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(Campo_email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Campo_senha, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(134, 134, 134)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkAdm)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(Campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(checkAdm)
                                    .addComponent(jLabel6)))))
                    .addComponent(Campo_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Campo_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_atualizar)
                    .addComponent(btn_editar)
                    .addComponent(btn_delete)
                    .addComponent(btn_adicionar))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
     List<Usuarios> lista = null;
        try {
            lista = CRUD.listarUsuarios();
        } catch (SQLException ex) {
            System.getLogger(Telaadm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
         DefaultTableModel modelo = new DefaultTableModel();
          modelo.addColumn("ID");
          modelo.addColumn("Nome");
          modelo.addColumn("Email");
          modelo.addColumn("Senha");
          modelo.addColumn("Admin");
          for (Usuarios u : lista) {
              modelo.addRow(new Object[]{
               u.getId(),
               u.getNome(),
               u.getEmail(),
               u.getSenha(),
               u.isAdm()
        });
    }
    tabelaUsuarios.setModel(modelo);
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int linhaSelecionada = tabelaUsuarios.getSelectedRow();

if (linhaSelecionada != -1) {

    int id = (int) tabelaUsuarios.getValueAt(linhaSelecionada, 0);

    try {
        Usuarios usuario = CRUD.buscarPorId(id);

        if (usuario != null) {

            if (usuario.isAdm()) {

                JOptionPane.showMessageDialog(this,
                        "Não é permitido excluir um administrador!");

            } else {

                CRUD.deletarUsuario(id);
                JOptionPane.showMessageDialog(this,
                        "Usuário excluído com sucesso!");

                atualizarTabela();
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
                "Erro ao excluir usuário!");
    }

} else {
    JOptionPane.showMessageDialog(this,
            "Selecione um usuário.");
}

    }//GEN-LAST:event_btn_deleteActionPerformed

    private void Campo_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_senhaActionPerformed

    private void Campo_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_emailActionPerformed

    private void checkAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAdmActionPerformed

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed
        String nome = Campo_nome.getText();
        String email = Campo_email.getText();
        String senha = new String(Campo_senha.getPassword());
        boolean adm; // se você estiver usando JCheckBox
        adm = checkAdm.isSelected();

            Usuarios u = new Usuarios(nome, email, senha, adm);

try {
    CRUD.cadastrarUsuarios(u);

    JOptionPane.showMessageDialog(this,
            "Usuário cadastrado com sucesso!");

    atualizarTabela();
    limparCampos();

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this,
            "Erro ao cadastrar usuário!");
}

    }//GEN-LAST:event_btn_adicionarActionPerformed

    private void tabelaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaUsuariosMouseClicked
        int linha = tabelaUsuarios.getSelectedRow();

    if (linha != -1) {

        Campo_nome.setText(tabelaUsuarios.getValueAt(linha, 1).toString());
        Campo_email.setText(tabelaUsuarios.getValueAt(linha, 2).toString());
        Campo_senha.setText(tabelaUsuarios.getValueAt(linha, 3).toString());

        boolean adm = (boolean) tabelaUsuarios.getValueAt(linha, 4);
        checkAdm.setSelected(adm);
    }
    }//GEN-LAST:event_tabelaUsuariosMouseClicked

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        int linhaSelecionada = tabelaUsuarios.getSelectedRow();

if (linhaSelecionada != -1) {

    int id = (int) tabelaUsuarios.getValueAt(linhaSelecionada, 0);

    String nome = Campo_nome.getText();
    String email = Campo_email.getText();
    String senha = new String(Campo_senha.getPassword());
    boolean adm = checkAdm.isSelected();

    Usuarios usuario = new Usuarios(id, nome, email, senha, adm);

    try {
        CRUD.editarUsuario(usuario);

        JOptionPane.showMessageDialog(this,
                "Usuário atualizado com sucesso!");

        atualizarTabela();
        limparCampos();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
                "Erro ao atualizar usuário!");
    }

} else {
    JOptionPane.showMessageDialog(this,
            "Selecione um usuário para editar.");
}

    }//GEN-LAST:event_btn_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Usuarios usuario = null;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Telaadm(usuario).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Campo_email;
    private javax.swing.JTextField Campo_nome;
    private javax.swing.JPasswordField Campo_senha;
    private javax.swing.JButton btn_adicionar;
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_editar;
    private javax.swing.JCheckBox checkAdm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaUsuarios;
    // End of variables declaration//GEN-END:variables
}
